name: Scala CI

on:
  push:
    paths:
      - 'src/**'
  pull_request:
    branches: [ main ]


  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: init and load data
        run: docker-compose -f src/test/docker/docker-compose.yml up -d
      - name: sleep
        run:  sleep 120
      - name: log
        run: docker logs docker_app_1